#!/bin/sh
cd "$(dirname "$0")"
export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
if [ ! -f /TICI ]; then
  export LD_LIBRARY_PATH="/data/openpilot/phonelibs/mapbox-gl-native-qt/aarch64:$LD_LIBRARY_PATH"
fi
export QT_PLUGIN_PATH="../../phonelibs/qt-plugins/$(uname -m)"
exec ./_ui
